[sdl]
fullscreen=false
output=surface
windowresolution=original
[dosbox]
machine=svga_s3
captures=capture
memsize=16
[render]
scaler=none
[cpu]
core=auto
cycles=fixed 60000
[mixer]
nosound=true
[sblaster]
sbtype=none
[speaker]
pcspeaker=false
[autoexec]
@echo off
rem Arbeitskopie des Originals, relativ zu tools/dosbox (von dort wird DOSBox gestartet)
mount c ../../../bmp-diff
c:
